In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [4]:
data = pd.read_csv("banknote-authentication.csv")
print("First 10 rows of the dataset:")
print(data.head(10))
print("\nDataset Dimensions:")
print(data.shape)
print("\nDescriptive Statistics:")
print(data.describe())


First 10 rows of the dataset:
   variance    skew  curtosis  entropy  class
0   3.62160  8.6661  -2.80730 -0.44699      0
1   4.54590  8.1674  -2.45860 -1.46210      0
2   3.86600 -2.6383   1.92420  0.10645      0
3   3.45660  9.5228  -4.01120 -3.59440      0
4   0.32924 -4.4552   4.57180 -0.98880      0
5   4.36840  9.6718  -3.96060 -3.16250      0
6   3.59120  3.0129   0.72888  0.56421      0
7   2.09220 -6.8100   8.46360 -0.60216      0
8   3.20320  5.7588  -0.75345 -0.61251      0
9   1.53560  9.1772  -2.27180 -0.73535      0

Dataset Dimensions:
(1372, 5)

Descriptive Statistics:
          variance         skew     curtosis      entropy        class
count  1372.000000  1372.000000  1372.000000  1372.000000  1372.000000
mean      0.433735     1.922353     1.397627    -1.191657     0.444606
std       2.842763     5.869047     4.310030     2.101013     0.497103
min      -7.042100   -13.773100    -5.286100    -8.548200     0.000000
25%      -1.773000    -1.708200    -1.574975    -2.41

In [6]:
X = data.drop(columns='class')
y = data['class']
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
clf = MLPClassifier(max_iter=500, activation='relu', random_state=42)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("\nPredictions with ReLU activation:")
print(pred)
cm = confusion_matrix(y_test, pred)
print("\nConfusion Matrix:")
print(cm)
cr = classification_report(y_test, pred)
print("\nClassification Report:")
print(cr)



Predictions with ReLU activation:
[0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1
 1 1 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0
 1 0 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1
 1 0 1 1 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 1 1
 1 0 1 1 1 0 1 0 1 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1
 0 1 1 0 0 1 0 0 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 1 0 0 0 1
 1 0 0 0 1 1 0 1 0 1 1 1 1 0 0 0]

Confusion Matrix:
[[148   0]
 [  0 127]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       148
           1       1.00      1.00      1.00       127

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [8]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = MLPClassifier(max_iter=500, activation='relu', random_state=42)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("\nConfusion Matrix with ReLU activation (70-30 split):")
print(confusion_matrix(y_test, pred))
print("\nClassification Report with ReLU activation (70-30 split):")
print(classification_report(y_test, pred))
clf = MLPClassifier(max_iter=500, activation='logistic', random_state=42)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("\nConfusion Matrix with Logistic activation (70-30 split):")
print(confusion_matrix(y_test, pred))



Confusion Matrix with ReLU activation (70-30 split):
[[229   0]
 [  0 183]]

Classification Report with ReLU activation (70-30 split):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       229
           1       1.00      1.00      1.00       183

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412


Confusion Matrix with Logistic activation (70-30 split):
[[229   0]
 [  1 182]]


In [10]:
print("\nClassification Report with Logistic activation (70-30 split):")
print(classification_report(y_test, pred))
clf = MLPClassifier(max_iter=500, activation='tanh', random_state=42)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("\nConfusion Matrix with Tanh activation (70-30 split):")
print(confusion_matrix(y_test, pred))
print("\nClassification Report with Tanh activation (70-30 split):")
print(classification_report(y_test, pred))
clf = MLPClassifier(max_iter=500, activation='identity', random_state=42)
clf.fit(x_train, y_train)
pred = clf.predict(x_test)
print("\nConfusion Matrix with Identity activation (70-30 split):")
print(confusion_matrix(y_test, pred))
print("\nClassification Report with Identity activation (70-30 split):")
print(classification_report(y_test, pred))



Classification Report with Logistic activation (70-30 split):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       229
           1       1.00      0.99      1.00       183

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412


Confusion Matrix with Tanh activation (70-30 split):
[[229   0]
 [  0 183]]

Classification Report with Tanh activation (70-30 split):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       229
           1       1.00      1.00      1.00       183

    accuracy                           1.00       412
   macro avg       1.00      1.00      1.00       412
weighted avg       1.00      1.00      1.00       412


Confusion Matrix with Identity activation (70-30 split):
[[226   3]
 [  2 181]]

Classification Report with Identity activation (70-30 split):
   